services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--providers.docker=true"
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--accesslog.fields.defaultmode=keep"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=gevernus@mail.ru"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
      - /etc/ssl/certs:/etc/ssl/certs:ro
    restart: unless-stopped
    networks:
      - web

  backend:
    platform: linux/amd64
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rim-auto-backend
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=7339549951:AAGGxOzdLf21mekkQ7Qo2s1Ug_ki1GOe2nY
      - MONGO_URL=mongodb://admin:va56dtw2!d@mongo:27017/?authSource=admin
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.backend.rule=Host(`casa-de-costura.ru`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
      # Route static files to backend as well
      - "traefik.http.routers.backend-static.rule=Host(`casa-de-costura.ru`) && PathPrefix(`/static`)"
      - "traefik.http.routers.backend-static.entrypoints=websecure"
      - "traefik.http.routers.backend-static.tls.certresolver=myresolver"
      - "traefik.http.routers.backend-static.priority=10"
      - "traefik.http.routers.backend-static.service=backend"
    volumes:
      - car_images:/app/static/images
    networks:
      - web
    depends_on:
      mongo:
        condition: service_started
      selenium:
        condition: service_started

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - VITE_API_URL=https://casa-de-costura.ru/api
        - VITE_TELEGRAM_BOT_USERNAME=${VITE_TELEGRAM_BOT_USERNAME}
    container_name: rim-auto-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - VITE_API_URL=https://casa-de-costura.ru/api
      - VITE_TELEGRAM_BOT_USERNAME=${VITE_TELEGRAM_BOT_USERNAME}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.frontend.rule=Host(`casa-de-costura.ru`) && PathPrefix(`/`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.priority=5"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    networks:
      - web
    depends_on:
      - backend

  selenium:
    image: selenium/standalone-chrome:4.34.0
    container_name: rim-auto-selenium
    restart: unless-stopped
    shm_size: 2gb
    environment:
      - SE_NODE_MAX_SESSIONS=2
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_SESSION_REQUEST_TIMEOUT=300
      - SE_SESSION_QUEUE_TIMEOUT=300
      - SE_NODE_SESSION_TIMEOUT=300
      - SE_VNC_NO_PASSWORD=1
    networks:
      - web

  mongo:
    image: mongo:8.0.12
    container_name: rim-auto-mongo
    command: mongod --quiet --logpath /dev/null
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: va56dtw2!d
    ports:
      - "27017:27017"
    networks:
      - web
    volumes:
      - mongo_data:/data/db
      - ./backups:/backups

volumes:
  mongo_data:
  car_images:

networks:
  web:
    driver: bridge
    name: web 